version: '3.8'
services:
  infoapp-mysql:
    container_name: mysql
    image: mysql:8.0.25
    environment:
      - MYSQL_DATABASE=infoapp
      - MYSQL_ROOT_PASSWORD=asdfghjkl
      - MYSQL_USER=comansys
      - MYSQL_PASSWORD=asdfghjkl
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  consul:
    container_name: consul
    image: consul:1.9.5
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:9.0.0
    volumes:
      - ./keycloak/realm-config:/opt/jboss/keycloak/realm-config
      - ./keycloak/keycloak-h2-data:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 9080:8080
      - 9443:9443
      - 10990:10990
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.profile.feature.upload_scripts=enabled'
      ]
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/asdfghjkl
